name: .NET-CORE6.0-UnitTest-CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AZURE_WEBAPP_NAME: appservice-manjeet
  AZURE_WEBAPP_PACKAGE_PATH: "app"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./.NetCore-Unit-Test/Finished solution
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./.NetCore-Unit-Test/Finished solution
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
#       working-directory: ./.NetCore-Unit-Test/Finished solution/EmployeeManagement.Test
#       continue-on-error: true
    - name: Build and publish projects
      run: |
       dotnet publish .NetCore-Unit-Test/Starter files/EmployeeManagement/EmployeeManagement.csproj -c Release -o website

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: website/**
        if-no-files-found: error
# #============CD=========================
#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download Artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: app
#           path: app

#       - name: Deploy to Azure
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ env.AZURE_WEBAPP_NAME }}
#           publish-profile: ${{ secrets.APP_SERVICE_SECRET }}
#           package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
