name: Build and Deploy to Azure Web App
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/build.yml@main
    with:
      package_directory: 'website/**'
 
  DEV:
    needs: build
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/release.yml@main
    with:
      environment: dev
      AZURE_WEBAPP_NAME: appservice-manjeet
      package_directory: 'BuildArtifacts'
    secrets:
      APP_SERVICE_SECRET: ${{ secrets.APP_SERVICE_SECRET }}
  QA:  
    needs: DEV
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/release.yml@main
    with:
      environment: QA
      AZURE_WEBAPP_NAME: appservice-manjeet
      package_directory: 'BuildArtifacts'
    secrets:
      APP_SERVICE_SECRET: ${{ secrets.APP_SERVICE_SECRET }}
  UAT:
    needs: QA
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/release.yml@main
    with:
      environment: UAT
      AZURE_WEBAPP_NAME: appservice-manjeet
      package_directory: 'BuildArtifacts'
    secrets:
      APP_SERVICE_SECRET: ${{ secrets.APP_SERVICE_SECRET }}'

  PROD:
    needs: UAT
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/release.yml@main
    with:
      environment: PROD
      AZURE_WEBAPP_NAME: appservice-manjeet
      package_directory: 'BuildArtifacts'
    secrets:
      APP_SERVICE_SECRET: ${{ secrets.APP_SERVICE_SECRET }}
