name: Build and Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/build.yml@main
    with:
      AZURE_WEBAPP_NAME : 'appservice-manjeet'
      package_directory: 'build'
 
  deploy-dev:
    needs: build
    secrets: inherit
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/release.yml@main
    with:
      environment: dev
      azure_credentials: ${{ secrets.APP_SERVICE_SECRET }}
      app_name: appservice-manjeet
      package_directory: 'build'

  deploy-qa:
    needs: build
    secrets: inherit
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/release.yml@main
    with:
      environment: QA
      azure_credentials: ${{ secrets.APP_SERVICE_SECRET }}
      app_name: appservice-manjeet
      package_directory: 'build'

  deploy-uat:
    needs: build
    secrets: inherit
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/release.yml@main
    with:
      environment: UAT
      azure_credentials: ${{ secrets.APP_SERVICE_SECRET }}
      app_name: appservice-manjeet
      package_directory: 'build'

  deploy-prod:
    needs: build
    secrets: inherit
    uses: manjeet-yadav123/Pipeline-Common/.github/workflows/release.yml@main
    with:
      environment: PROD
      azure_credentials: ${{ secrets.APP_SERVICE_SECRET }}
      app_name: appservice-manjeet
      package_directory: 'build'
